name: Deploy

on: [push]

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            DATABASE_URL: ${{secrets.DATABASE_URL}}
            AUTH_SECRET: ${{secrets.AUTH_SECRET}}
            AUTH_GITHUB_ID: ${{secrets.AUTH_GITHUB_ID}}
            AUTH_GITHUB_SECRET: ${{secrets.AUTH_GITHUB_SECRET}}
            AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
            AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: "22"

            - name: Install dependencies
              run: npm ci

            - name: Deploy
              run: |
                npx prisma generate
                npx sst deploy --stage production